version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/semin/data/wordpress
  db:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/semin/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/wordpress
    networks:
      - app-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - app-network
    restart: always
